### ISSUE TITLE
how to build in android studio 2.3?

### ISSUE THREAD

**Issue by DavidHan008** [mtbii/RobotCA#3]
hi , this app is very cool , but i do not know how to build in android studio 2.3, can you help me

**Comment by mtbii** [comment]
This app is no longer maintained. It's very likely you will have to change the build paths to ROS Kinetic to get it to run in the latest versions of Android Studio.

See https://github.com/ros-autom/RobotCA. They've updated it to Kinetic on their kenetic branch and have instructions to get it to run in Android Studio there.
